<div class="container shadow rounded col-8 mt-5 p-1">
    <div class="w-100 text-center">
        <h1 class="h3 my-3 fw-normal">Add a Customer</h1>
    </div>
    <form class="w-100 col container" action="/AddCustomer" method="POST">
        <div class="row mb-2 g-2">
            <div class="form-floating col-sm-4">
                <input type="text" class="form-control" name="firstName" placeholder="First Name"
                       aria-label="Staff Name" aria-describedby="basic-addon1" min="0" required>
                <label for="form-name">Staff Name</label>
            </div>
            <div class="form-floating col-sm-4">
                <input type="Text" class="form-control" name="lastName" placeholder="Last Name"
                       aria-label="lastName">
                <label for="form-name">Last Name</label>
            </div>
            <div class="form-floating col-sm-4">
                <input type="Text" class="form-control" name="phoneNumber" placeholder="Phone Number"
                       aria-label="lastName">
                <label for="form-name">Phone number</label>
            </div>
        </div>
        <div class="row mb-2 g-2">
            <div class="form-floating col">
				<textarea class="form-control" name="email" id="emailTextArea" rows="3" style="height: 5em;"
                          required></textarea>
                <label for="emailTextArea" class="form-label">Email</label>
            </div>
        </div>
        <div class="row mb-2 g-2">
            <div class="col d-flex justify-content-center">
                <button class="btn btn-primary" type="submit" name="submitBTN" value="Submit Problem">Submit</button>
            </div>
        </div>
    </form>
</div>