<div class="container shadow rounded col-8 mt-5 p-1">
    <div class="w-100 text-center">
        <h1 class="h3 my-3 fw-normal">Add a User</h1>
    </div>
    <form class="w-100 col container" action="/AddUser" method="POST">
        <div class="row mb-2 g-2">
            <div class="form-floating col-sm-4">
                <input type="number" class="form-control" name="Staff_Name" placeholder="Staff Name"
                       aria-label="Staff Name" aria-describedby="basic-addon1" min="0" required>
                <label for="form-name">Staff Name</label>
            </div>
            <div class="form-floating col-sm-4">
                <select class="form-select pb-2" name="permissions" id="floating-category" required>
                    <option value="1">Admin</option>
                    <option value="2">Team manager</option>
                    <option value="0">No permissions</option>
                </select>
                <label for="floating-category">Staff Permissions</label>
            </div>
            <div class="form-floating col-sm-4">
                <input type="number" class="form-control" name="Password" placeholder="Password"
                       aria-label="Password" aria-describedby="basic-addon1" min="0" required>
                <label for="form-name">Password</label>
            </div>
        </div>
        <div class="row mb-2 g-2">
            <div class="form-floating col">
				<textarea class="form-control" name="email" id="emailTextArea" rows="3" style="height: 5em;"
                          required></textarea>
                <label for="emailTextArea" class="form-label">Email</label>
            </div>
        </div>
        <div class="row mb-2 g-2">
            <div class="col d-flex justify-content-center">
                <button class="btn btn-primary" type="submit" name="submitBTN" value="Submit Problem">Submit</button>
            </div>
        </div>
    </form>
</div>