<div class="container shadow rounded col-3 mt-5 p-1">
    <div class="w-100 text-center mb-3">
        <h1 class="h3 my-3 fw-normal">Error 404</h1>
        <p1>The page you were looking for cannot be found</p1>
    </div>
    <div class="justify-content-center d-flex mb-3">
        <form action="/" method="get">
            <button class="btn btn-primary" type="submit">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-arrow-return-left" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                          d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5z"/>
                </svg>
                Return Home
            </button>
        </form>
    </div>
</div>
