<div class="container">
    <div class="row">
        <div class="container shadow rounded col-5 mt-5 p-2">
            <div class="w-100 text-center">
                <h1 class="h3 my-3 fw-normal">Your Activity</h1>
            </div>
        </div>
        <div class="container shadow rounded col-5 mt-5 p-2">
            <div class="w-100 text-center">
                <h1 class="h3 my-3 fw-normal">Team Activity</h1>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="container shadow rounded col-11 mt-5 p-2">
            <div class="w-100 text-center">
                <h1 class="h3 my-3 fw-normal">Reminders</h1>
            </div>
        </div>
    </div>
</div>

<div class="container shadow rounded col-8 mt-5 p-1">
    <div class="justify-content-left mb-5">
        <?php /** @var ProblemModel $active_problems */
        foreach ($view->problemDataSet as $active_problems) {
            $active_problems ->display();
        }
        ?>
    </div>
</div>
