<?php
	require_once __DIR__ . "/Templates/head.phtml";
	require_once __DIR__ . "/Templates/header.phtml";
?>

<div class="container border border-2 rounded col-4 mt-5">
	<div class="d-flex justify-content-center mb-2">
		<h1 class="h3 mt-5 fw-normal">Sign in</h1>
	</div>
	<div class="d-flex justify-content-center mb-5">
		<form class="row row-cols-lg-auto g-3 align-items-center form-horizontal" action="login" method="POST">
				<div class="form-floating">
					<label for="form-name">Email</label>
					<input type="email" name="email" class="form-control" id="form-name" placeholder="name@example.com" required>
				</div>
				<div class="form-floating">
					<label for="form-password">Password</label>
					<input type="password" name="password" class="form-control" id="form-password" placeholder="password" readonly>
				</div>
				<button type="submit" class="btn btn-primary">Login</button>
		</form>
	</div>
</div>
