<div class="container shadow rounded col-8 my-5 p1">
	<?php
		/** @var ViewBase $view */
		$view->problem->display();
	?>
	<style>
		#comments>.comment:before {
			position: absolute;
			top: calc(-1rem - 1px);
			left: 10px;
			background-color: rgba(0,0,0,.125);
			display: block;
			width: 2px;
			content: "";
			height: calc(100% + 1rem);
			z-index: -1;
		}
		
		#comments>.comment:last-child:before {
			height: calc(100% + 2rem + 2px);
		}

		#comments>.comment {
		}
	</style>
	<div class="container px-3" id="comments">
		<?php
			/** @var CommentModel $comment */
			foreach($view->current_comments as $comment) {
				$comment->display();
			}
		?>
	</div>
	<div class="card m-3">
		<div class="card-header">
			<h5 class="mb-0">Add a comment</h5>
		</div>
		<div class="card-body">
			<form id="comment-form" action="/Comment" method="post">
				<div class="form-floating">
					<textarea class="form-control" name="comment-text" id="comment-textarea"
										style="max-height: 250px; min-height: 5em; overflow: hidden" required></textarea>
					<label for="comment-textarea">Leave a comment</label>
				</div>
				<div class="d-flex justify-content-end">
					<button type="submit" class="btn btn-primary mt-3">Comment</button>
				</div>
			</form>
		</div>
	</div>
</div>

<script>
	let form = document.getElementById("comment-form");
	let text_area = document.getElementById("comment-textarea");
	let comments_container = document.getElementById("comments");

	let post_comment = new XMLHttpRequest();
	
	post_comment.onload = function () {

		if (post_comment.status === 200) {
			comments_container.insertAdjacentHTML("beforeend", post_comment.responseText);
		} else if (post_comment.status === 400) {
			alert("2")
		} else {
			// Something else happened
			alert("3")
		}
	};

	form.addEventListener("submit" ,(event) => {
		event.preventDefault();
		
		post_comment.open("POST", "/Comment");
		
		post_comment.setRequestHeader("Cache-Control", "no-cache, no-store, max-age=0");
		post_comment.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
		
		post_comment.send(`problem_id=<?php echo $view->problem->id; ?>&add_comment=true&comment_text=${encodeURIComponent(text_area.value)}`);
		text_area.value = "";
	});
	
	let get_new_comments = new XMLHttpRequest();
	
	get_new_comments.onload = function () {
		if (get_new_comments.status === 200) {
			comments_container.insertAdjacentHTML("beforeend", get_new_comments.responseText);
		} else if (post_comment.status === 400) {
			alert("2")
		} else if (post_comment.status === 204) {
			// No new comments
		} else {
		
		}
	}
	
	setInterval(function () {
		
		let time_stamp = document.querySelector(".comment:last-child").getAttribute("data-time-stamp");
		
		get_new_comments.open("GET", `/Comment?new_comments=true&problem_id=<?php echo $view->problem->id; ?>&now=${time_stamp}`);

		get_new_comments.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
		
		get_new_comments.send(null);
	}, 5000);
</script>