
<div class="container shadow rounded col-8 mt-5 p-1">
<div id="searchSection" class = "justify-content-center">
        <form class = "" action="SearchBar" method="GET">

            <div class="row">

                <h1 class="text-center">Search for:</h1>

            </div>

            <div class="row justify-content-center">
            <!--Search Bar-->
                <div class="col-10" id="searchBar">
                    <input class="inline form-control" id="searchBarProper" type="text" name="searchBar">

                </div>
            </div>

            <div id="filters" class="row justify-content-center container my-4">



                <div id="radioButtons" class="col-4">
                    <!--Radio Button - Customer-->
                    <input class="Radio" id="Radio_Customer" type="radio" name="searchRadio" value="1" onchange="disableCheck()" checked="checked">
                    <label for="Radio_Customer">Customer</label>

                    <!--Radio Button - Problem-->
                    <input class="Radio" id="Radio_Problem" type="radio" name="searchRadio" value="2" onchange="disableCheck()">
                    <label for="Radio_Problem">Problem</label>

                    <!--Radio Button - Category-->
                    <input class="Radio" id="Radio_Category" type="radio" name="searchRadio" value="3" onchange="disableCheck()">
                    <label for="Radio_Category">Category</label>

                    <!--Radio Button - Staff-->
                    <input class="Radio" id="Radio_Staff" type="radio" name="searchRadio" value="4" onchange="disableCheck()">
                    <label for="Radio_Staff">Colleague</label>
                </div>



                <!--Select Dropdown-->
                <select name="urgencyDropdown" id="urgencyID" class="col-4">
                    <option value="">All</option>
                    <option value="High">High</option>
                    <option value="Medium">Medium</option>
                    <option value="Low">Low</option>
                </select>

                <!--Checkbox-->
                <div class="form-check form-switch col-4 " id="switch">
                    <input class="form-check-input" id="flexSwitchCheckChecked" type="checkbox" name="searchCheckbox"
                           value="1">
                    <label for="Check_If_Resolved">Resolved</label>
                </div>
            </div>

            <div class="row justify-content-center my-4">
                <div class="col-4 ">
                    <button class="inline btn btn-outline-danger col-12 display-6" id="searchSubmit" type="submit" name="submitSearchButton" style="height: 2em;font-size: 1.5em;">Submit</button>
                </div>
            </div>
        </div>
    </form>

</div>
</div>

    <?php

    switch ($view->searchRequest) {

        // Customer
        case "1":
        {

            // Post what the user has just searched for.
            if ($view->searchRequest === "")
            {

                foreach ($view->dataset as $lot) {

                    echo"<h1>\"".$view->searchLine."\"</h1>";

                }

            }
            else
            {

                echo "<h1>All Customers</h1>";

            }

            foreach ($view->dataset as $lot) {

                echo
                '

                <div id="Customer_Info">

                    <p id="">First Name: ' . $lot->getFirstName() . '</p>
                    <p id="">Surname: ' . $lot->getLastName() . '</p>
                    <p id="">Queries Pending: ' . $lot->getQueryCount() . '</p>
                    <p><a class = "btn btn-outline-danger" href="/ViewCustomer?customerID='.$lot->getCustomerID().'">link</a></p>
                
                </div>
                
                ';

            }

            break;

        }

        // Problem
        case "2":
        {

            // Post what the user has just searched for.
            if ($view->searchRequest === "")
            {

                echo "<h1>" . '"' . $view->searchLine . '"' . "</h1>";

            }
            else
            {

                echo "<h1>All Queries</h1>";

            }

            foreach ($view->dataset as $lot) {

                echo
                '

                <div id="Query_Post_Problem">

                    <h1 id="id">' . $lot->getProblemID() . '</h1>
            
                    <p id="category">Category: ' . $lot->getCategory() . '</p>
                    <p id="description">Description: ' . $lot->getDescription() . '</p>
                    <p id="urgency">Urgency: ' . $lot->getUrgency() . '</p>
                    <p id="added">Added: ' . $lot->getAddedTime() . '</p>
                    <p id="resolved">Resolved: ' . $lot->getResolved() . '</p>
                    <p id="staff">Colleague: ' . $lot->getStaffName() . '</p>
            
                </div>
                
                ';

                }

            break;

        }

        // Category
        case "3":
        {

            // Post what the user has just searched for.
            if ($view->searchRequest === "")
            {

                echo "<h1>" . '"' . $view->searchLine . '"' . "</h1>";

            }
            else
            {

                echo "<h1>All Queries</h1>";

            }

            foreach ($view->dataset as $lot) {

                echo
                '

                <div id="Query_Post_Category">

                    <h1 id="id">' . $lot->getProblemID() . '</h1>
            
                    <p id="category">Category: ' . $lot->getCategory() . '</p>
                    <p id="description">Description: ' . $lot->getDescription() . '</p>
                    <p id="urgency">Urgency: ' . $lot->getUrgency() . '</p>
                    <p id="added">Added: ' . $lot->getAddedTime() . '</p>
                    <p id="resolved">Resolved: ' . $lot->getResolved() . '</p>
                    <p id="staff">Colleague: ' . $lot->getStaffName() . '</p>
            
                </div>
                
                ';

            }

            break;

        }

        // Staff
        case "4":
        {

            // Post what the user has just searched for.
            if ($view->searchRequest === "")
            {

                echo "<h1>" . '"' . $view->searchLine . '"' . "</h1>";

            }
            else
            {

                echo "<h1>All Queries</h1>";

            }

            foreach ($view->dataset as $lot) {

                echo
                '

                <div id="Query_Post_Staff">

                    <h1 id="id">' . $lot->getProblemID() . '</h1>
            
                    <p id="category">Category: ' . $lot->getCategory() . '</p>
                    <p id="description">Description: ' . $lot->getDescription() . '</p>
                    <p id="urgency">Urgency: ' . $lot->getUrgency() . '</p>
                    <p id="added">Added: ' . $lot->getAddedTime() . '</p>
                    <p id="resolved">Resolved: ' . $lot->getResolved() . '</p>
                    <p id="staff">Colleague: ' . $lot->getStaffName() . '</p>
            
                </div>
                
                ';

            }

            break;

        }

    }

?>

</div>