<?php

$radioValue = "1";
$dropValue = "nothing";

if(isset($_GET['searchRadio']))
{

    $this->radioValue = $_GET['searchRadio'];

}
else
{

    $this->radioValue = "1";

}

if(isset($_GET['urgencyDropdown']))
{

    $this->dropValue = $_GET['urgencyDropdown'];

}
else
{

    $this->dropValue = "nothing";

}

?>
<div class="container shadow rounded col-8 mt-5 p-1">
<div id="searchSection" class = "justify-content-center">
        <form class = "" action="SearchBar" method="GET">

            <div class="row">

                <h1 class="text-center">Search for:</h1>

            </div>

            <div class="row justify-content-center">
            <!--Search Bar-->
                <div class="col-10" id="searchBar">
                    <input class="inline form-control" id="searchBarProper" type="text" name="searchBar">

                </div>
            </div>

            <div id="filters" class="row justify-content-center container my-4">

            <div id="filters" class="row justify-content-center container my-4">


                <div id="radioButtons" class="col-4">
                    <!--Radio Button - Customer-->
                    <input class="Radio" id="Radio_Customer" type="radio" name="searchRadio" value="1" <?php if ($this->radioValue === "1") {echo' checked="checked"';}?>>
                    <label for="Radio_Customer">Customer</label>

                    <!--Radio Button - Problem-->
                    <input class="Radio" id="Radio_Problem" type="radio" name="searchRadio" value="2" <?php if ($this->radioValue === "2") {echo' checked="checked"';}?>>
                    <label for="Radio_Problem">Problem</label>

                    <!--Radio Button - Category-->
                    <input class="Radio" id="Radio_Category" type="radio" name="searchRadio" value="3" <?php if ($this->radioValue === "3") {echo' checked="checked"';}?>>
                    <label for="Radio_Category">Category</label>

                    <!--Radio Button - Staff-->
                    <input class="Radio" id="Radio_Staff" type="radio" name="searchRadio" value="4" <?php if ($this->radioValue === "4") {echo' checked="checked"';}?>>
                    <label for="Radio_Staff">Colleague</label>
                </div>

                <!--Select Dropdown-->
                <select name="urgencyDropdown" id="urgencyID" class="col-4">
                    <option value=""        <?php if ($this->dropValue === "") {echo' selected="selected"';}?>>All</option>
                    <option value="High"    <?php if ($this->dropValue === "High") {echo' selected="selected"';}?>>High</option>
                    <option value="Medium"  <?php if ($this->dropValue === "Medium") {echo' selected="selected"';}?>>Medium</option>
                    <option value="Low"     <?php if ($this->dropValue === "Low") {echo' selected="selected"';}?>>Low</option>
                </select>

                <!--Checkbox-->
                <div class="col-4 justify-content-center">
                    <div class="form-check form-switch mx-5" id="switch">
                        <input class="form-check-input" id="flexSwitchCheckChecked" type="checkbox" name="searchCheckbox" value="1" <?php if (isset($_GET['searchCheckbox'])) {echo' checked="checked"';}?>>
                        <label for="Check_If_Resolved">Resolved</label>
                    </div>
                </div>
            </div>

            <div class="row justify-content-center my-4">
                <div class="col-4 ">
                    <button class="inline btn btn-outline-danger col-12 " id="searchSubmit" type="submit" name="submitSearchButton" style="height: 2em;font-size: 1.5em;">Submit</button>
                </div>
            </div>
        </div>
    </form>

</div>
</div>

    <?php

    switch ($view->searchRequest) {

        // Customer
        case "1":
        {

            // Post what the user has just searched for.
            if ($view->searchLine != "")
            {

                echo"
                    <div class='container shadow rounded col-8 mt-5 p-1'>
                    
                        <div class='w-100 text-center'>
                            <h1 class='h3 my-3 fw-normal'>\"$view->searchLine\"</h1>
                        </div>



";

            }
            else
            {

                echo "

                <div class='container shadow rounded col-8 mt-5 p-1'>

                    <div class='w-100 text-center'>
		                <h1 class='h3 my-3 fw-normal'>All Customers</h1>
	                </div>
                    ";
            }

            foreach ($view->dataset as $lot) {

                echo
                '

                <div id="Customer_Info" class="container border rounded shadow my-3">
                
                <div class="container text-center my-3">

                    <div class="row">
                            <p class="col-6 h4">First Name: ' . $lot->getFirstName() . '</p>
                            <p class="col-6 h4">Surname: ' . $lot->getLastName() . '</p>
                    </div>
                    <div class="row">
                    <p class="col-12 h4">Queries Pending: ' . $lot->getQueryCount() . '</p>
                     </div>
                     <div class="row justify-content-center">
                     <p ><a class = "inline btn btn-outline-danger col-4 " href="/ViewCustomer?customerID='.$lot->getCustomerID().'">More info</a></p>
                   </div>
                </div>
                </div>
                
                ';

            }

            break;

        }

        // Problem
        case "2":
        {

            // Post what the user has just searched for.
            if ($view->searchLine != "")
            {

                echo"<div class='container shadow rounded col-8 mt-5 p-1'>
                    
                        <div class='w-100 text-center'>
                            <h1 class='h3 my-3 fw-normal'>\"$view->searchLine\"</h1>
                        </div>";

            }
            else
            {

                echo "<div class='container shadow rounded col-8 mt-5 p-1'>

                    <div class='w-100 text-center'>
		                <h1 class='h3 my-3 fw-normal'>All Problems</h1>
	                </div>";

            }

            foreach ($view->dataset as $lot) {

                echo
                '

                <div id="Query_Post_Problem" class="container border rounded shadow my-3">

                    <h1 id="id">' . $lot->getProblemID() . '</h1>
            
                    <p id="category">Category: ' . $lot->getCategory() . '</p>
                    <p id="description">Description: ' . $lot->getDescription() . '</p>
                    <p id="urgency">Urgency: ' . $lot->getUrgency() . '</p>
                    <p id="added">Added: ' . $lot->getAddedTime() . '</p>
                    <p id="resolved">Resolved: ' . $lot->getResolved() . '</p>
                    <p id="staff">Colleague: ' . $lot->getStaffName() . '</p>
            
                </div>
                
                
                
                ';

                }

            break;

        }

        // Category
        case "3":
        {

            // Post what the user has just searched for.
            if ($view->searchLine != "")
            {

                echo"<div class='container shadow rounded col-8 mt-5 p-1'>
                    
                        <div class='w-100 text-center'>
                            <h1 class='h3 my-3 fw-normal'>\"$view->searchLine\"</h1>
                        </div>";

            }
            else
            {

                echo "<div class='container shadow rounded col-8 mt-5 p-1'>

                    <div class='w-100 text-center'>
		                <h1 class='h3 my-3 fw-normal'>All Problems</h1>
	                </div>";

            }

            foreach ($view->dataset as $lot) {

                echo
                '

                <div id="Query_Post_Category" class="container border rounded shadow my-3">

                    <h1 id="id">' . $lot->getProblemID() . '</h1>
            
                    <p id="category">Category: ' . $lot->getCategory() . '</p>
                    <p id="description">Description: ' . $lot->getDescription() . '</p>
                    <p id="urgency">Urgency: ' . $lot->getUrgency() . '</p>
                    <p id="added">Added: ' . $lot->getAddedTime() . '</p>
                    <p id="resolved">Resolved: ' . $lot->getResolved() . '</p>
                    <p id="staff">Colleague: ' . $lot->getStaffName() . '</p>
            
                </div>
                
                ';

            }

            break;

        }

        // Staff
        case "4":
        {

            // Post what the user has just searched for.
            if ($view->searchLine != "")
            {

                echo"<div class='container shadow rounded col-8 mt-5 p-1'>
                    
                        <div class='w-100 text-center'>
                            <h1 class='h3 my-3 fw-normal'>\"$view->searchLine\"</h1>
                        </div>";

            }
            else
            {

                echo "<div class='container shadow rounded col-8 mt-5 p-1'>

                    <div class='w-100 text-center'>
		                <h1 class='h3 my-3 fw-normal'>All Problems</h1>
	                </div>";

            }

            foreach ($view->dataset as $lot) {

                echo
                '

                <div id="Query_Post_Staff" class="container border rounded shadow my-3">

                    <h1 id="id">' . $lot->getProblemID() . '</h1>
            
                    <p id="category">Category: ' . $lot->getCategory() . '</p>
                    <p id="description">Description: ' . $lot->getDescription() . '</p>
                    <p id="urgency">Urgency: ' . $lot->getUrgency() . '</p>
                    <p id="added">Added: ' . $lot->getAddedTime() . '</p>
                    <p id="resolved">Resolved: ' . $lot->getResolved() . '</p>
                    <p id="staff">Colleague: ' . $lot->getStaffName() . '</p>
            
                </div>
                
                ';

            }

            break;

        }

    }

?>

</div>