<?php
	$customer_id_validation_class = isset($_SESSION["invalid_customer_id"]) && $_SESSION["invalid_customer_id"] ? "is-invalid" : "";
?>

<div class="container shadow rounded col-8 mt-5 p-1">
	<div class="w-100 text-center">
		<h1 class="h3 my-3 fw-normal">Update a Problem</h1>
	</div>
	<form class="w-100 col container" action="/UpdateProblem" method="POST">
		<div class="row mb-2 g-2">
			<div class="form-floating col-sm-4">
				<select class="form-select pb-2" name="urgency" id="floating-urgency" required>
					<option value="Low">Low</option>
					<option value="Medium">Medium</option>
					<option value="High">High</option>
				</select>
				<label for="floating-urgency">Problem Urgency</label>
			</div>
			<div class="form-floating col-sm-4">
				<select class="form-select pb-2" name="categorisation_id" id="floating-category" required>
					<option value="1">Password Queries</option>
					<option value="2">Login Issues</option>
					<option value="3">Process Queries</option>
					<option value="4">Transfers In</option>
					<option value="5">Withdrawals</option>
					<option value="6">Benefits</option>
					<option value="7">New Business Applications</option>
					<option value="8">Complaints</option>
				</select>
				<label for="floating-category">Problem Category</label>
			</div>
			<div class="form-floating col-sm-4">
				<input type="number" class="form-control <?php echo $customer_id_validation_class; ?>" name="CustomerID" placeholder="Customer ID"
							 aria-label="Customer ID" aria-describedby="basic-addon1" min="0" required>
				<label for="form-name">Customer ID</label>
				<?php if(isset($_SESSION["invalid_customer_id"])): ?>
					<div class="invalid-feedback">
						Customer with that ID does not exist.
					</div>
				<?php endif;
					unset($_SESSION["invalid_customer_id"]);
				?>
			</div>
		</div>
		<div class="row mb-2 g-2">
			<div class="form-floating col">
				<textarea class="form-control" name="description" id="descriptionTextArea" rows="3" style="height: 5em;"
									required></textarea>
				<label for="descriptionTextArea" class="form-label">Problem Description</label>
			</div>
		</div>
		<div class="row mb-2 g-2">
			<div class="col d-flex justify-content-center">
				<button class="btn btn-primary" type="submit" name="submitBTN" value="Submit Problem">Submit</button>
			</div>
		</div>
		<?php if(isset($_SESSION["update_problem_message"])): ?>
			<div class="row mb-2 g-2">
				<div class="col d-flex justify-content-center">
					<p class="text-danger fw-bold" ><?php echo $_SESSION["update_problem_message"]; ?></p>
				</div>
			</div>
		<?php endif;
			unset($_SESSION["update_problem_message"]);
		?>
	</form>
</div>