<?php
	require_once "Core/ProblemCategories.php";
	/** @var object $view */
?>
<div class="container shadow rounded col-8 mt-5 p-1">
	<div class="w-100 text-center">
		<h1 class="h3 my-3 fw-normal">Update a Problem</h1>
	</div>
	<form class="w-100 col container" action="/UpdateProblem" method="post">
		<input type="hidden" name="problem-id" value="<?= $view->id ?>">
		<div class="row mb-2 g-2">
			<div class="form-floating col-sm-4">
				<select class="form-select pb-2" name="problem-urgency" id="floating-urgency" required>
					<?php
						foreach (["Low", "Medium", "High"] as $urgency)
						{
							$selected = $view->problem->urgency === $urgency ? "selected" : "";
							echo "<option value=\"$urgency\" $selected>$urgency</option>";
						}
					?>
				</select>
				<label for="floating-urgency">Problem Urgency</label>
			</div>
			<div class="form-floating col-sm-4">
				<select class="form-select pb-2" name="problem-category-id" id="floating-category" required>
					<?php
						for ($x = 1; $x <= ProblemCategories::$category_count; $x++)
						{
							$selected = $view->problem->category_id === $x ? "selected" : "";
							echo "<option value=\"$x\" $selected>" . ProblemCategories::get_category_name_by_id($x) . "</option>";
						}
					?>
				</select>
				<label for="floating-category">Problem Category</label>
			</div>
			<div class="form-floating col-sm-4">
				<input type="number" class="form-control" name="problem-customer-id" placeholder=""
							 value="<?php echo $view->problem->customer_id; ?>"
							 aria-label="Customer ID" aria-describedby="basic-addon1" min="0" required>
				<label for="form-name">Customer ID</label>
			</div>
		</div>
		<div class="row mb-2 g-2">
			<div class="form-floating col">
				<textarea class="form-control" name="problem-description" id="descriptionTextArea" rows="3" style="height: 5em;"
									required><?php echo $view->problem->description; ?></textarea>
				<label for="descriptionTextArea" class="form-label">Problem Description</label>
			</div>
		</div>

		<div class="row mb-2 g-2">
			<div class="d-flex flex-fill">
				<button class="btn btn-outline-success col-1 mx-1" name="resolveButton" value="Resolve">Resolve</button>
				<div class="col d-flex justify-content-end flex-fill">
					<button class="btn btn-primary" type="submit" name="submitBTN" value="Submit Problem">Submit</button>
				</div>
			</div>
		</div>
	</form>
</div>