<div class="container shadow rounded col-4 mt-5 p-1">
    <div class="w-100 text-center">
        <h1 class="h3 my-3 fw-normal">Upload Audio File</h1>
    </div>
    <form class="w-100 col container" enctype="multipart/form-data" action="uploadAudio" method="post">
        <div class="row mb-2 g-2">
            <div class="form-floating col-sm-12">
                <input type="number" class="form-control" name="problem_id" placeholder="Problem ID" id="form-problem-id"
                aria-label="Problem ID" aria-describedby="basic-addon1" required>
                <label for="form-problem-id">Problem ID</label>
            </div>
        </div>
        <div class="row mb-2 g-2">
            <div class="custom-file col-sm-12">
                <input type="file" class="form-control" id="file-upload" name="file" accept="audio/*" lang="en">
            </div>
        </div>
        <div class="row mb-2 g-2">
            <div class="col d-flex justify-content-center">
                <button class="btn btn-primary" type="submit" name="submit">Upload</button>
            </div>
        </div>
    </form>
    <?php
    if (isset($_SESSION["file-upload-message"]))
    {
        echo $_SESSION["file-upload-message"];
        unset($_SESSION["file-upload-message"]);
    }
    ?>
</div>