<?php

echo('

    <div id="Customer_Info" class="container border rounded shadow my-3">
                
        <div class="container text-center my-3">
    
            <div class="row">
            
                <p class="col-6 h4">First Name: ' . $view->customer->getCustomerFirstName() . '</p>
                <p class="col-6 h4">Surname: ' . $view->customer->getCustomerLastName() . '</p>
                    
            </div>
            
            <div class="row">
            
                <p class="col-12 h4">Email: ' . $view->customer->getCustomerEmail() . '</p>
                <p class="col-12 h4">Phone Number: ' . $view->customer->getCustomerPhoneNumber() . '</p>
            
            </div>
           
        </div>
	
    </div>

');

foreach ($view->datasetOfProblems as $lot) {

    // Purely for the view, the boolean 0 or 1 is changed to "Yes" or "No" before display.
    if($lot->getResolved() === "0")
    {$resolvedStatus = "Yes";}
    else
    {$resolvedStatus = "No";}

    echo
        '

        <div id="Query_Post_Problem" class="container border rounded shadow my-3">
                
            <div class="container text-center my-3">
        
                <div class="row">
                
                    <p class="col-6 h4">Category: ' . $lot->getCategory() . '</p>
                    <p class="col-6 h4">Urgency: ' . $lot->getUrgency() . '</p>
                        
                </div>
                
                <div class="row">
                
                    <p class="col-12 h4">Added: ' . $lot->getAddedTime() . '</p>
                    <p class="col-12 h4">Resolved: ' . $resolvedStatus . '</p>
                
                </div>
                 
                <div class="row justify-content-center">
                 
                    <p><a class = "inline btn btn-outline-danger col-4 " href="/Problem?id=' . $lot->getProblemID() . '">More info</a></p>
                 
                </div>
               
            </div>
                        
        </div>
                
    ';

}

?>


