<?php
	/** @var CommentModel $comment */
	/** @var UserModel $staff */
?>
<div class="card justify-content-left mt-3 mb-3 comment" data-time-stamp="<?php echo $comment->time_stamp->format("Y-m-d H:i:s");  ?>">
	<div class="card-header d-flex pe-1">
		<h5 class="mb-0"><?php echo $staff->name; ?></h5>
	</div>
	<div class="card-body">
		<?php echo $comment->text; ?>
	</div>
	<div class="card-footer">
		<div class="d-flex justify-content-end flex-fill">
			<p class="text-muted mb-0"><?php echo $comment->time_stamp->format("Y-m-d H:i:s"); ?></p>
		</div>
	</div>
</div>