<footer class="footer mt-auto py-3" style="background-color: #C51230;">
	<div class="container">
		<div class="d-flex flex-column" style="color: white;">
			<div class="p-0 d-flex justify-content-center">
				<img class="mx-auto d-block" style="height: 40px" src="/Assets/A_J_Bell_white_on_red.jpg" alt="AJ Bell" />
			</div>
			<div class="p-0 d-flex justify-content-center">
				<p>Copyright © 2021 AJBell</p>
			</div>
			<div class="p-0 d-flex justify-content-center">
				<div class="d-flex justify-content-center">
					<p class="text-decoration-none" style="width: 7em; text-align: end">
						<a class="text-dark" href="../privacy.php">Privacy Policy</a>
					</p>
					<span style="border: 1px solid black; border-left-width: 0; width: 1px; height: 1.75rem;" class="mx-1"></span>
					<p style="width: 7em;">
						<a class="text-dark" href="../legal.php">Legal stuff</a>
					</p>
				</div>
			</div>
		</div>
	</div>
</footer>