<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #C51230;">
	<div class="container-fluid">
		<a class="navbar-brand" href="/">Complaints Procedure Centre</a>
		<button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse"
						data-bs-target="#navbar" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbar">
			<ul class="navbar-nav me-auto mb-2 mb-lg-0">
				<li class="nav-item">
					<a class="nav-link" aria-current="page" href="/">Home</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" aria-current="page" href="<?php echo "/AddProblem" ?>">Add Problem</a>
				</li>
			</ul>
			
			<?php if (isset($_SESSION["logged-in"]) && $_SESSION["logged-in"]): ?>
				<!-- Don't show the search bar if we aren't logged in. -->
				<form class="d-flex m-0">
					<input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
					<button class="btn btn-success" type="submit">Search</button>
				</form>
			<?php endif ?>
		</div>
	</div>
</nav>
